# reference run: https://wandb.ai/gmayanksharan-google/cirrus/runs/ak69pj10
sft:
  max_num_epochs: 1
  max_num_steps: 1127
  val_period: 100
  val_batches: 16
  val_global_batch_size: 128
  val_micro_batch_size: 2
  val_at_start: true
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: "results/sft_qwen3_8b_openr1_math"
  metric_name: val_loss
  higher_is_better: false
  save_period: 1000
  keep_top_k: null
policy:
  model_name: "Qwen/Qwen3-8B-Base"
  tokenizer:
    name: "Qwen/Qwen3-8B"
    chat_template: "default"
  train_global_batch_size: 64
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 8192
  precision: bfloat16

  dtensor_cfg:
    enabled: false
  
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    activation_checkpointing: true
    converter_type: "Qwen2ForCausalLM"
    tensor_model_parallel_size: 1
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    sequence_parallel: true
    freeze_moe_router: true
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "none" # "seq_aux_loss" causes logprob error divergence for grpo
    moe_router_bias_update_rate: 0.0 # by default, disable bias updates for grpo
    #gives ~20% training perf speedup with sequence packing 
    apply_rope_fusion: True

    optimizer:
      optimizer: "adam"
      lr: 1.17e-05
      min_lr: 1.17e-6
      weight_decay: 0.1
      bf16: true
      fp16: false
      params_dtype: "float32"

      #adam
      adam_beta1: 0.9
      adam_beta2: 0.95
      adam_eps: 1e-6

      #distributed optimizer
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true

      clip_grad: 1.0
      optimizer_cpu_offload: false
      optimizer_offload_fraction: 0.0

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "cosine"
      lr_decay_iters: 1127
      lr_warmup_iters: 100
      lr_warmup_init: 1.17e-7

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      use_custom_fsdp: false
      data_parallel_sharding_strategy: "optim_grads_params"

  dynamic_batching:
    enabled: False

  sequence_packing:
    enabled: True
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64

  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  max_grad_norm: 1
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 1.17e-05
      weight_decay: 0.1
      betas:
        - 0.9
        - 0.95
      eps: 1e-06
      foreach: false
      fused: false
  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.01
        end_factor: 1.0
        total_iters: 100
    - name: "torch.optim.lr_scheduler.CosineAnnealingLR"
      kwargs:
        T_max: 1127
        eta_min: 1.17e-6
    - milestones: [100]
data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "dataset_mixture"
  # the original dataset is located in /mnt/dataset/cirrus0.0/
  mixture:
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_amc_aime_qwen3_8b_no_thinking/train-unboxed*"
      samples: 523
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_aops_forum_qwen3_8b_no_thinking/train-unboxed*"
      samples: 5510
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_cn_contest_qwen3_8b_no_thinking/train-unboxed*"
      samples: 6227
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_inequalities_qwen3_8b_no_thinking/train-unboxed*"
      samples: 573
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_number_theory_qwen3_8b_no_thinking/train-unboxed*"
      samples: 175
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_olympiads_qwen3_8b_no_thinking/train-unboxed*"
      samples: 39280
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_olympiads_ref_qwen3_8b_no_thinking/train-unboxed*"
      samples: 422
      additional_kwargs:
        split: "train"
    - file_format: "huggingface"
      name_or_paths: "allenai/tulu-3-sft-personas-instruction-following"
      samples: 29980
      additional_kwargs:
        split: "train"
  add_bos: true
  add_eos: true
  add_generation_prompt: false
logger:
  log_dir: "logs/sft_qwen3_8b_openr1_math_non_thinking"
  wandb_enabled: true
  tensorboard_enabled: false
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: cirrus
    name: sft_qwen3_8b_openr1_math_non_thinking
  gpu_monitoring:
    collection_interval: 30
    flush_interval: 30
cluster:
  gpus_per_node: 8
  num_nodes: 4
