# reference run: https://wandb.ai/gmayanksharan-google/cirrus/runs/1fy0dcpm
sft:
  max_num_epochs: 1
  max_num_steps: 5000
  val_period: 100
  val_batches: 32
  val_global_batch_size: 32
  val_micro_batch_size: 2
  val_at_start: true
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: "results/sft_qwen3_8b_openr1_math_code_swe"
  metric_name: val_loss
  higher_is_better: false
  save_period: 1000
  keep_top_k: null
policy:
  model_name: "Qwen/Qwen3-8B-Base"
  tokenizer:
    name: "Qwen/Qwen3-8B"
    chat_template: "default"
  train_global_batch_size: 32
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 32768
  precision: bfloat16

  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: false
    activation_checkpointing: true
    tensor_parallel_size: 8
    context_parallel_size: 1
    custom_parallel_plan: null
  dynamic_batching:
    enabled: True
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    logprob_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.logprob_batch_size}}
    sequence_length_round: 64
  sequence_packing:
    enabled: False
  make_sequence_length_divisible_by: ${policy.dtensor_cfg.tensor_parallel_size}
  max_grad_norm: 1
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 1.11e-05
      weight_decay: 0.1
      betas:
        - 0.9
        - 0.95
      eps: 1e-06
      foreach: false
      fused: false
  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.01
        end_factor: 1.0
        total_iters: 100
    - name: "torch.optim.lr_scheduler.CosineAnnealingLR"
      kwargs:
        T_max: 1240
        eta_min: 1.11e-6
    - milestones: [100]
data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "dataset_mixture"
  # the original dataset is located in /mnt/dataset/cirrus0.0/
  mixture:
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_amc_aime_qwen3_8b_no_thinking/train-unboxed*"
      samples: 523
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_aops_forum_qwen3_8b_no_thinking/train-unboxed*"
      samples: 5510
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_cn_contest_qwen3_8b_no_thinking/train-unboxed*"
      samples: 6227
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_inequalities_qwen3_8b_no_thinking/train-unboxed*"
      samples: 573
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_number_theory_qwen3_8b_no_thinking/train-unboxed*"
      samples: 175
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_olympiads_qwen3_8b_no_thinking/train-unboxed*"
      samples: 39280
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_olympiads_ref_qwen3_8b_no_thinking/train-unboxed*"
      samples: 422
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_verifiable_code_taco_qwen3_8b_code_no_thinking/train-augmented*"
      samples: 4104
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_verifiable_code_code_contests_qwen3_8b_code_no_thinking/train-augmented*"
      samples: 1725
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_verifiable_code_apps_qwen3_8b_code_no_thinking/train-augmented*"
      samples: 1817
      additional_kwargs:
        split: "train"
    - file_format: "huggingface"
      name_or_paths: "allenai/tulu-3-sft-personas-instruction-following"
      samples: 29980
      additional_kwargs:
        split: "train"
    - file_format: "huggingface"
      name_or_paths: "hellomlp/SWE-bench-all__style-3__fs-oracle"
      samples: 17868
      additional_kwargs:
        split: "train"
  add_bos: true
  add_eos: true
  add_generation_prompt: false
logger:
  log_dir: "logs/sft_qwen3_8b_openr1_math_code_swe_non_thinking"
  wandb_enabled: true
  tensorboard_enabled: false
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: fei-cirrus
    name: sft_qwen3_8b_openr1_math_code_swe_non_thinking
  gpu_monitoring:
    collection_interval: 30
    flush_interval: 30
cluster:
  gpus_per_node: 8
  num_nodes: 4
